[build]
publish = "public"
command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo"

[context.production.environment]
HUGO_VERSION = "0.75.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.75.0"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.75.0"

